# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sword.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
    name='sword.proto',
    package='sword',
    syntax='proto3',
    serialized_options=None,
    serialized_pb=b'\n\x0bsword.proto\x12\x05sword\"\x1a\n\x07Message\x12\x0f\n\x07message\x18\x01 \x01(\t\"4\n\x0fMessageResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x10\n\x08received\x18\x02 \x01(\x08\x32\x46\n\x05Sword\x12=\n\x11GetServerResponse\x12\x0e.sword.Message\x1a\x16.sword.MessageResponse\"\x00\x62\x06proto3'
)

_MESSAGE = _descriptor.Descriptor(
    name='Message',
    full_name='sword.Message',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='message', full_name='sword.Message.message', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=22,
    serialized_end=48,
)

_MESSAGERESPONSE = _descriptor.Descriptor(
    name='MessageResponse',
    full_name='sword.MessageResponse',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='message', full_name='sword.MessageResponse.message', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='received', full_name='sword.MessageResponse.received', index=1,
            number=2, type=8, cpp_type=7, label=1,
            has_default_value=False, default_value=False,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=50,
    serialized_end=102,
)

DESCRIPTOR.message_types_by_name['Message'] = _MESSAGE
DESCRIPTOR.message_types_by_name['MessageResponse'] = _MESSAGERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), {
    'DESCRIPTOR': _MESSAGE,
    '__module__': 'sword_pb2'
    # @@protoc_insertion_point(class_scope:sword.Message)
})
_sym_db.RegisterMessage(Message)

MessageResponse = _reflection.GeneratedProtocolMessageType('MessageResponse', (_message.Message,), {
    'DESCRIPTOR': _MESSAGERESPONSE,
    '__module__': 'sword_pb2'
    # @@protoc_insertion_point(class_scope:sword.MessageResponse)
})
_sym_db.RegisterMessage(MessageResponse)
#
# DESCRIPTOR.has_options = True
# DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\033io.grpc.examples.helloworldB\017HelloWorldProtoP\001\242\002\003HLW'))


_SWORD = _descriptor.ServiceDescriptor(
    name='Sword',
    full_name='sword.Sword',
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    serialized_start=104,
    serialized_end=174,
    methods=[
        _descriptor.MethodDescriptor(
            name='GetServerResponse',
            full_name='sword.Sword.GetServerResponse',
            index=0,
            containing_service=None,
            input_type=_MESSAGE,
            output_type=_MESSAGERESPONSE,
            serialized_options=None,
        ),
    ])
_sym_db.RegisterServiceDescriptor(_SWORD)

DESCRIPTOR.services_by_name['Sword'] = _SWORD

# @@protoc_insertion_point(module_scope)
